# Generated by Django 4.0.4 on 2022-04-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_address_remove_order_notice_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
    ]
